<!DOCTYPE html>
<html lang="en">

<head>
    <script>
        let num = 4;
        let prom1 = new Promise((resolve, reject) => { (num == 4) ? resolve("prom1 OK") : reject("prom1 NOT OK"); });


        prom1
            .then((x) => {
                console.log(x);
                return "I am a parameter to the chained promise";
            })  //function for resolve -> EVERY THEN RETURNS A NEW PROMISE (VOID PROMISE BY DEFAULT)
            .then((z) => {
                console.log(z);
                throw new Error("I have an error"); // will execute the catch statement
            })
            .then(() => console.log("second chain"))
            .catch((y) => console.log("I am in catch: "+y))  //function for reject


/*
OUTPUT:
_______________________________

prom1 OK
I am a parameter to the chained promise
I am in catch: Error: I have an error
*/
    </script>
</head>

<body>

</body>

</html>